## Imports de biblioteca e acesso ao Google Drive

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


## Montando o Dataset

In [3]:
path_to_ds = '/content/drive/MyDrive/IA/candidatos.csv'
df = pd.read_csv(path_to_ds)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000
8        one         6.0                6   40000

In [4]:
def number_to_int(number):
  if number == 'zero':
    return 0
  elif number == 'one':
    return 1
  elif number == 'two':
    return 2
  elif number == 'three':
    return 3
  elif number == 'four':
    return 4
  elif number == 'five':
    return 5
  elif number == 'six':
    return 6
  elif number == 'seven':
    return 7
  elif number == 'eight':
    return 8
  elif number == 'nine':
    return 9
  elif number == 'ten':
    return 10
  elif number == 'eleven':
    return 11
  else:
    return number

def int_to_number(integer):
  if integer == 0:
    return 'zero'
  elif integer == 1:
    return 'one'
  elif integer == 2:
    return 'two'
  elif integer == 3:
    return 'three'
  elif integer == 4:
    return 'four'
  elif integer == 5:
    return 'five'
  elif integer == 6:
    return 'six'
  elif integer == 7:
    return 'seven'
  elif integer == 8:
    return 'eight'
  elif integer == 9:
    return 'nine'
  elif integer == 10:
    return 'ten'
  elif integer == 11:
    return 'eleven'
  else:
    return integer
  
def len_without_nan(lst):
  length = 0
  for l in lst:
    if not math.isnan(l):
      length += 1
  return length

def sum_without_nan(lst):
  sum = 0
  for l in lst:
    if not math.isnan(l):
      sum += l
  return sum

In [5]:
experience = df['experience']

experience_2 = []
for e in experience:
  experience_2.append(number_to_int(e))

df['experience'] = experience_2

len_experience = len_without_nan(experience_2)
sum_experience = sum_without_nan(experience_2)

avg_experience = math.floor(sum_experience / len_experience)
df['experience'] = df['experience'].fillna(avg_experience)

In [6]:
avg_test_score = math.floor(df['test_score'].median())
df['test_score'] = df['test_score'].fillna(avg_test_score)

In [7]:
df

experience  test_score  interview_score  salary
0         5.0         8.0                9   50000
1         5.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         7.0                7   72000
7        11.0         7.0                8   80000
8         1.0         6.0                6   40000

## Regressão Linear

In [8]:
reg = linear_model.LinearRegression()

In [9]:
reg.fit(df[['experience', 'test_score', 'interview_score']], df['salary'])

LinearRegression()

In [10]:
reg.coef_

array([3175.33729962, 1484.14084228, 2982.64223288])

In [11]:
applicant = [[6, 8, 7]]
reg.predict(applicant)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([60879.71071888])

In [12]:
applicant2 = [[1, 1, 1]]
reg.predict(applicant2)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([16718.1849275])